/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    Chat: typeof import('./src/components/Chat.vue')['default']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    IconDownload: typeof import('./src/components/Icon/Download.vue')['default']
    IconUpload: typeof import('./src/components/Icon/Upload.vue')['default']
    Markdown: typeof import('./src/components/Markdown.vue')['default']
    Profile: typeof import('./src/components/Profile.vue')['default']
  }
}
